// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnBgYSiosOtL-YfRiJWVx99wtz3bupIq4',
    appId: '1:403059314947:web:8a142d88047ba8ba691936',
    messagingSenderId: '403059314947',
    projectId: 'fitmar-cb74f',
    authDomain: 'fitmar-cb74f.firebaseapp.com',
    storageBucket: 'fitmar-cb74f.appspot.com',
    measurementId: 'G-DVDSLK2C02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWwn5Chpryg7wtLl0DodsWGvKi4FSafuc',
    appId: '1:403059314947:android:aaec2a3e6a33ef87691936',
    messagingSenderId: '403059314947',
    projectId: 'fitmar-cb74f',
    storageBucket: 'fitmar-cb74f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLuf0t_95ZI2zlOBYlrWhQk77GDwad-pI',
    appId: '1:403059314947:ios:a85b3d46d648f537691936',
    messagingSenderId: '403059314947',
    projectId: 'fitmar-cb74f',
    storageBucket: 'fitmar-cb74f.appspot.com',
    iosBundleId: 'com.example.fitmar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLuf0t_95ZI2zlOBYlrWhQk77GDwad-pI',
    appId: '1:403059314947:ios:a85b3d46d648f537691936',
    messagingSenderId: '403059314947',
    projectId: 'fitmar-cb74f',
    storageBucket: 'fitmar-cb74f.appspot.com',
    iosBundleId: 'com.example.fitmar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnBgYSiosOtL-YfRiJWVx99wtz3bupIq4',
    appId: '1:403059314947:web:7361e3e24c256e3d691936',
    messagingSenderId: '403059314947',
    projectId: 'fitmar-cb74f',
    authDomain: 'fitmar-cb74f.firebaseapp.com',
    storageBucket: 'fitmar-cb74f.appspot.com',
    measurementId: 'G-7DHTJ4M1ZN',
  );
}
